### ISSUE TITLE
Who's alive ?

### ISSUE THREAD

**Issue by darkgusgus** [darkgusgus/HungerGames#11]
http://ohivtrem.co.nf/viewtopic.php?f=26&t=71#p372

Could be pretty neat. We can debate on how else we can work this out

**Comment by darkgusgus** [comment]
#30

**Comment by jkent** [comment]
We've now got a WP_DEAD icon that shows if a player is dead.

**Comment by darkgusgus** [comment]
Me Gusta, can't wait to see that.
