### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by darkgusgus** [darkgusgus/HungerGames#14]
Have random tips every minute

**Comment by jkent** [comment]
I don't understand this, can you elaborate?

**Comment by darkgusgus** [comment]
Sorry. I tend to write notes only for myself :P 

Basically like a tutorial system. Every minute a tip is displayed on cp.

**Comment by Foe-of-Eternity** [comment]
Are you sure about CP? it might be better to push to chat.

**Comment by darkgusgus** [comment]
Urf, you're right not !CP...

The best would be the same chat used to announce winner at the end.

trap_SendServerCommand( -1, va("print \"___"") );
