### ISSUE TITLE
Life drain at 5 minutes

### ISSUE THREAD

**Issue by darkgusgus** [darkgusgus/HungerGames#5]
Once everyone is dead and people hide, the game doesn't move. So we want to make them do something. Maybe they can drain life from others.

https://code.google.com/p/cqvm/source/browse/trunk/src/game/g_main.c?r=57
Keyword: vampire

**Comment by jkent** [comment]
code snippet: http://pastebin.com/bHFzp9Vs

**Comment by darkgusgus** [comment]
Alternate plan is to give spectators !slap

**Comment by darkgusgus** [comment]
I opened a topic on forums to debate on the topic

http://ohivtrem.co.nf/viewtopic.php?f=23&t=73#p380

**Comment by darkgusgus** [comment]
Closing this for now. Helmets will be used to find campers
