### ISSUE TITLE
Hide name tags

### ISSUE THREAD

**Issue by darkgusgus** [darkgusgus/HungerGames#6]
To prevent easy alliances, we can remove name tags. I'm pretty sure i've seen somewhere in trem something about name tags. Any ideas ?

**Comment by darkgusgus** [comment]
Apparently we need to mod cgame. Not in my plans to make players download stuff other than map.

**Comment by jkent** [comment]
closing since we marked it as wontfix

**Comment by jkent** [comment]
Since we're working on the cgame now, this issue is relevant again.
